//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSharpLayers {
    
    
    public partial class Webform1 {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// Panel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Panel1;
        
        /// <summary>
        /// toolBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel toolBar1;
        
        /// <summary>
        /// Panel1_MapHostExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.MapHostExtender Panel1_MapHostExtender;
        
        /// <summary>
        /// editTool1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Controls.Edit.EditingTools editTool1;
        
        /// <summary>
        /// layerSwitcherTool1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Controls.LayerSwitcher.LayerSwitcherTool layerSwitcherTool1;
        
        /// <summary>
        /// TmsLayerComponent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Layers.Tms.TmsLayerComponent TmsLayerComponent1;
        
        /// <summary>
        /// WmsLayerComponent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Layers.Wms.WmsLayerComponent WmsLayerComponent1;
        
        /// <summary>
        /// VectorLayerComponent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Layers.Vector.VectorLayerComponent VectorLayerComponent1;
        
        /// <summary>
        /// vector2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Layers.Vector.VectorLayerComponent vector2;
        
        /// <summary>
        /// httpProtocol control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Protocol.Http.HttpProtocolComponent httpProtocol;
    }
}
