//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpMap.Demo.SharpLayers {
    
    
    public partial class Webform1 {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// mapPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel mapPanel1;
        
        /// <summary>
        /// stylemap1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Styles.SldComponent stylemap1;
        
        /// <summary>
        /// Panel1_MapHostExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.MapHostExtender Panel1_MapHostExtender;
        
        /// <summary>
        /// editTool1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Controls.Edit.EditingTools editTool1;
        
        /// <summary>
        /// layerSwitcherTool1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Controls.LayerSwitcher.LayerSwitcherTool layerSwitcherTool1;
        
        /// <summary>
        /// GenericOLControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Controls.GenericOLControl GenericOLControl1;
        
        /// <summary>
        /// GenericOLControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Controls.GenericOLControl GenericOLControl2;
        
        /// <summary>
        /// WmsLayerComponent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Layers.Wms.WmsLayerComponent WmsLayerComponent1;
        
        /// <summary>
        /// VectorLayerComponent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharpMap.Presentation.Web.SharpLayers.Layers.Vector.VectorLayerComponent VectorLayerComponent1;
    }
}
