//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Osm
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class osm
    {
        private string generatorField;
        private ItemsChoiceType[] itemsElementNameField;
        private object[] itemsField;

        private string versionField;

        public osm()
        {
            versionField = "0.6";
        }

        /// <remarks/>
        [XmlElement("api", typeof (api))]
        [XmlElement("changeset", typeof (changeset))]
        [XmlElement("gpx_file", typeof (gpx_file))]
        [XmlElement("node", typeof (node))]
        [XmlElement("preferences", typeof (preferences))]
        [XmlElement("relation", typeof (relation))]
        [XmlElement("user", typeof (user))]
        [XmlElement("way", typeof (way))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore]
        public ItemsChoiceType[] ItemsElementName
        {
            get { return itemsElementNameField; }
            set { itemsElementNameField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string version
        {
            get { return versionField; }
            set { versionField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string generator
        {
            get { return generatorField; }
            set { generatorField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class api
    {
        private area areaField;

        private tracepoints tracepointsField;
        private version versionField;

        private waynodes waynodesField;

        /// <remarks/>
        public version version
        {
            get { return versionField; }
            set { versionField = value; }
        }

        /// <remarks/>
        public area area
        {
            get { return areaField; }
            set { areaField = value; }
        }

        /// <remarks/>
        public tracepoints tracepoints
        {
            get { return tracepointsField; }
            set { tracepointsField = value; }
        }

        /// <remarks/>
        public waynodes waynodes
        {
            get { return waynodesField; }
            set { waynodesField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class version
    {
        private string maximumField;
        private string minimumField;

        /// <remarks/>
        [XmlAttribute]
        public string minimum
        {
            get { return minimumField; }
            set { minimumField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string maximum
        {
            get { return maximumField; }
            set { maximumField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class area
    {
        private string maximumField;

        /// <remarks/>
        [XmlAttribute]
        public string maximum
        {
            get { return maximumField; }
            set { maximumField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class tracepoints
    {
        private string per_pageField;

        /// <remarks/>
        [XmlAttribute]
        public string per_page
        {
            get { return per_pageField; }
            set { per_pageField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class waynodes
    {
        private string maximumField;

        /// <remarks/>
        [XmlAttribute]
        public string maximum
        {
            get { return maximumField; }
            set { maximumField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class changeset
    {
        private tag[] tagField;

        /// <remarks/>
        [XmlElement("tag")]
        public tag[] tag
        {
            get { return tagField; }
            set { tagField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class tag
    {
        private string kField;

        private string vField;

        /// <remarks/>
        [XmlAttribute]
        public string k
        {
            get { return kField; }
            set { kField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string v
        {
            get { return vField; }
            set { vField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class gpx_file
    {
        private string idField;

        private string latField;

        private string lonField;
        private string nameField;

        private gpx_filePending pendingField;
        private gpx_filePublic publicField;

        private string timestampField;
        private string userField;

        public gpx_file()
        {
            publicField = gpx_filePublic.@false;
            pendingField = gpx_filePending.@false;
        }

        /// <remarks/>
        [XmlAttribute]
        public string id
        {
            get { return idField; }
            set { idField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string lat
        {
            get { return latField; }
            set { latField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string lon
        {
            get { return lonField; }
            set { lonField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string user
        {
            get { return userField; }
            set { userField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        [DefaultValue(gpx_filePublic.@false)]
        public gpx_filePublic @public
        {
            get { return publicField; }
            set { publicField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        [DefaultValue(gpx_filePending.@false)]
        public gpx_filePending pending
        {
            get { return pendingField; }
            set { pendingField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string timestamp
        {
            get { return timestampField; }
            set { timestampField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum gpx_filePublic
    {
        /// <remarks/>
        @true,

        /// <remarks/>
        @false,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum gpx_filePending
    {
        /// <remarks/>
        @true,

        /// <remarks/>
        @false,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class node
    {
        private string changesetField;
        private string idField;

        private string latField;

        private string lonField;
        private tag[] tagField;

        private string timestampField;
        private string userField;
        private nodeVisible visibleField;

        /// <remarks/>
        [XmlElement("tag")]
        public tag[] tag
        {
            get { return tagField; }
            set { tagField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string id
        {
            get { return idField; }
            set { idField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string lat
        {
            get { return latField; }
            set { latField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string lon
        {
            get { return lonField; }
            set { lonField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string changeset
        {
            get { return changesetField; }
            set { changesetField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public nodeVisible visible
        {
            get { return visibleField; }
            set { visibleField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string user
        {
            get { return userField; }
            set { userField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string timestamp
        {
            get { return timestampField; }
            set { timestampField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum nodeVisible
    {
        /// <remarks/>
        @true,

        /// <remarks/>
        @false,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class preferences
    {
        private tag[] tagField;

        /// <remarks/>
        [XmlElement("tag")]
        public tag[] tag
        {
            get { return tagField; }
            set { tagField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class relation
    {
        private string changesetField;
        private string idField;
        private object[] itemsField;

        private string timestampField;
        private string userField;
        private string visibleField;

        /// <remarks/>
        [XmlElement("member", typeof (member))]
        [XmlElement("tag", typeof (tag))]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string id
        {
            get { return idField; }
            set { idField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string changeset
        {
            get { return changesetField; }
            set { changesetField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string visible
        {
            get { return visibleField; }
            set { visibleField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string user
        {
            get { return userField; }
            set { userField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string timestamp
        {
            get { return timestampField; }
            set { timestampField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class member
    {
        private string refField;

        private string roleField;
        private memberType typeField;

        /// <remarks/>
        [XmlAttribute]
        public memberType type
        {
            get { return typeField; }
            set { typeField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string @ref
        {
            get { return refField; }
            set { refField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string role
        {
            get { return roleField; }
            set { roleField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum memberType
    {
        /// <remarks/>
        way,

        /// <remarks/>
        node,

        /// <remarks/>
        relation,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class user
    {
        private string account_createdField;
        private string display_nameField;
        private home homeField;

        /// <remarks/>
        public home home
        {
            get { return homeField; }
            set { homeField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string display_name
        {
            get { return display_nameField; }
            set { display_nameField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string account_created
        {
            get { return account_createdField; }
            set { account_createdField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class home
    {
        private string latField;

        private string lonField;

        private string zoomField;

        /// <remarks/>
        [XmlAttribute]
        public string lat
        {
            get { return latField; }
            set { latField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string lon
        {
            get { return lonField; }
            set { lonField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string zoom
        {
            get { return zoomField; }
            set { zoomField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class way
    {
        private string changesetField;
        private string idField;
        private object[] itemsField;
        private nd nd1Field;
        private nd ndField;

        private tag[] tag1Field;
        private tag[] tagField;

        private string timestampField;
        private string userField;
        private wayVisible visibleField;

        /// <remarks/>
        [XmlElement("tag", Order = 0)]
        public tag[] tag
        {
            get { return tagField; }
            set { tagField = value; }
        }

        /// <remarks/>
        [XmlElement(Order = 1)]
        public nd nd
        {
            get { return ndField; }
            set { ndField = value; }
        }

        /// <remarks/>
        [XmlElement("tag", Order = 2)]
        public tag[] tag1
        {
            get { return tag1Field; }
            set { tag1Field = value; }
        }

        /// <remarks/>
        [XmlElement("nd", Order = 3)]
        public nd nd1
        {
            get { return nd1Field; }
            set { nd1Field = value; }
        }

        /// <remarks/>
        [XmlElement("nd", typeof (nd), Order = 4)]
        [XmlElement("tag", typeof (tag), Order = 4)]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string id
        {
            get { return idField; }
            set { idField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string changeset
        {
            get { return changesetField; }
            set { changesetField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public wayVisible visible
        {
            get { return visibleField; }
            set { visibleField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string user
        {
            get { return userField; }
            set { userField = value; }
        }

        /// <remarks/>
        [XmlAttribute]
        public string timestamp
        {
            get { return timestampField; }
            set { timestampField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class nd
    {
        private string refField;

        /// <remarks/>
        [XmlAttribute]
        public string @ref
        {
            get { return refField; }
            set { refField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum wayVisible
    {
        /// <remarks/>
        @true,

        /// <remarks/>
        @false,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [XmlType(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {
        /// <remarks/>
        api,

        /// <remarks/>
        changeset,

        /// <remarks/>
        gpx_file,

        /// <remarks/>
        node,

        /// <remarks/>
        preferences,

        /// <remarks/>
        relation,

        /// <remarks/>
        user,

        /// <remarks/>
        way,
    }
}