//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

namespace SharpMap.Symbology.Serialization
{



    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnaryLogicOpType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinaryLogicOpType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    public abstract partial class LogicOpsType
    {
    }

    public partial class UnaryLogicOpType : LogicOpsType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Xml.Serialization.XmlRootAttribute("And", Namespace = "http://www.opengis.net/ogc", IsNullable = false)]
    public partial class BinaryLogicOpType : LogicOpsType
    {

        private object[] itemsField;

        private ItemsChoiceType6[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("And", typeof(BinaryLogicOpType))]
        [System.Xml.Serialization.XmlElementAttribute("Not", typeof(UnaryLogicOpType))]
        [System.Xml.Serialization.XmlElementAttribute("Or", typeof(BinaryLogicOpType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyIsBetween", typeof(PropertyIsBetweenType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyIsEqualTo", typeof(BinaryComparisonOpType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyIsGreaterThan", typeof(BinaryComparisonOpType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyIsGreaterThanOrEqualTo", typeof(BinaryComparisonOpType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyIsLessThan", typeof(BinaryComparisonOpType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyIsLessThanOrEqualTo", typeof(BinaryComparisonOpType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyIsLike", typeof(PropertyIsLikeType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyIsNotEqualTo", typeof(BinaryComparisonOpType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyIsNull", typeof(PropertyIsNullType))]
        [System.Xml.Serialization.XmlElementAttribute("comparisonOps", typeof(ComparisonOpsType))]
        [System.Xml.Serialization.XmlElementAttribute("logicOps", typeof(LogicOpsType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType6[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Xml.Serialization.XmlRootAttribute("Add", Namespace = "http://www.opengis.net/ogc", IsNullable = false)]
    public partial class BinaryOperatorType : ExpressionType
    {

        private ExpressionType[] itemsField;

        private ItemsChoiceType1[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Add", typeof(BinaryOperatorType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Div", typeof(BinaryOperatorType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Function", typeof(FunctionType1), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Literal", typeof(LiteralType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Mul", typeof(BinaryOperatorType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("PropertyName", typeof(PropertyNameType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Sub", typeof(BinaryOperatorType), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public ExpressionType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Xml.Serialization.XmlRootAttribute("PropertyIsEqualTo", Namespace = "http://www.opengis.net/ogc", IsNullable = false)]
    public partial class BinaryComparisonOpType : ComparisonOpsType
    {

        private ExpressionType[] itemsField;

        private ItemsChoiceType5[] itemsElementNameField;

        private bool matchCaseField;

        public BinaryComparisonOpType()
        {
            this.matchCaseField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Add", typeof(BinaryOperatorType))]
        [System.Xml.Serialization.XmlElementAttribute("Div", typeof(BinaryOperatorType))]
        [System.Xml.Serialization.XmlElementAttribute("Function", typeof(FunctionType1))]
        [System.Xml.Serialization.XmlElementAttribute("Literal", typeof(LiteralType))]
        [System.Xml.Serialization.XmlElementAttribute("Mul", typeof(BinaryOperatorType))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyName", typeof(PropertyNameType))]
        [System.Xml.Serialization.XmlElementAttribute("Sub", typeof(BinaryOperatorType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public ExpressionType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType5[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool matchCase
        {
            get
            {
                return this.matchCaseField;
            }
            set
            {
                this.matchCaseField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc", IncludeInSchema = false)]
    public enum ItemsChoiceType6
    {

        /// <remarks/>
        And,

        /// <remarks/>
        Not,

        /// <remarks/>
        Or,

        /// <remarks/>
        PropertyIsBetween,

        /// <remarks/>
        PropertyIsEqualTo,

        /// <remarks/>
        PropertyIsGreaterThan,

        /// <remarks/>
        PropertyIsGreaterThanOrEqualTo,

        /// <remarks/>
        PropertyIsLessThan,

        /// <remarks/>
        PropertyIsLessThanOrEqualTo,

        /// <remarks/>
        PropertyIsLike,

        /// <remarks/>
        PropertyIsNotEqualTo,

        /// <remarks/>
        PropertyIsNull,

        /// <remarks/>
        comparisonOps,

        /// <remarks/>
        logicOps,
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("Geometry", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class GeometryType
    {

        private PropertyNameType propertyNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ogc")]
        public PropertyNameType PropertyName
        {
            get
            {
                return this.propertyNameField;
            }
            set
            {
                this.propertyNameField = value;
            }
        }
    }

    /// <remarks/>
    public partial class StrokeType
    {

    }

    public partial class GraphicFillType
    {

    }

    public partial class GraphicType
    {
    }

    public partial class ExternalGraphicType
    {

    }


    public partial class MarkType
    {
    }

    public partial class FillType
    {
    }

    public partial class SvgParameterType : ParameterValueType
    {

    }

    public partial class AnchorPointType
    {

    }

    public partial class DisplacementType
    {

    }

    public partial class GraphicStrokeType
    {

    }

    public partial class PolygonSymbolizerType : SymbolizerType
    {
    }

    public partial class PointSymbolizerType : SymbolizerType
    {
    }

    public partial class TextSymbolizerType : SymbolizerType
    {
    }

    public partial class LabelPlacementType
    {
    }

    public partial class LinePlacementType
    {
    }

    public partial class PointPlacementType
    {

    }

    public partial class HaloType
    {
    }

    public partial class FontType
    {
    }

    public partial class RasterSymbolizerType : SymbolizerType
    {
    }

    public partial class ChannelSelectionType
    {

    }

    public partial class SelectedChannelType
    {

    }

    public partial class ContrastEnhancementType
    {

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("Histogram", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class HistogramType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("Normalize", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class NormalizeType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se", IncludeInSchema = false)]
    public enum ItemsChoiceType4
    {

        /// <remarks/>
        BlueChannel,

        /// <remarks/>
        GrayChannel,

        /// <remarks/>
        GreenChannel,

        /// <remarks/>
        RedChannel,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public enum OverlapBehavior
    {

        /// <remarks/>
        LATEST_ON_TOP,

        /// <remarks/>
        EARLIEST_ON_TOP,

        /// <remarks/>
        AVERAGE,

        /// <remarks/>
        RANDOM,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("ColorMap", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class ColorMapType
    {

        private FunctionType itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categorize", typeof(CategorizeType))]
        [System.Xml.Serialization.XmlElementAttribute("Interpolate", typeof(InterpolateType))]
        public FunctionType Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("Categorize", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class CategorizeType : FunctionType
    {

        private ParameterValueType lookupValueField;

        private ParameterValueType valueField;

        private ParameterValueType[] thresholdField;

        private ParameterValueType[] value1Field;

        private ThreshholdsBelongToType threshholdsBelongToField;

        private bool threshholdsBelongToFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterValueType LookupValue
        {
            get
            {
                return this.lookupValueField;
            }
            set
            {
                this.lookupValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ParameterValueType Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Threshold", Order = 2)]
        public ParameterValueType[] Threshold
        {
            get
            {
                return this.thresholdField;
            }
            set
            {
                this.thresholdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order = 3)]
        public ParameterValueType[] Value1
        {
            get
            {
                return this.value1Field;
            }
            set
            {
                this.value1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ThreshholdsBelongToType threshholdsBelongTo
        {
            get
            {
                return this.threshholdsBelongToField;
            }
            set
            {
                this.threshholdsBelongToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool threshholdsBelongToSpecified
        {
            get
            {
                return this.threshholdsBelongToFieldSpecified;
            }
            set
            {
                this.threshholdsBelongToFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    public enum ThreshholdsBelongToType
    {

        /// <remarks/>
        succeeding,

        /// <remarks/>
        preceding,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("Interpolate", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class InterpolateType : FunctionType
    {

        private ParameterValueType lookupValueField;

        private InterpolationPointType[] interpolationPointField;

        private ModeType modeField;

        private bool modeFieldSpecified;

        private MethodType methodField;

        private bool methodFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterValueType LookupValue
        {
            get
            {
                return this.lookupValueField;
            }
            set
            {
                this.lookupValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterpolationPoint", Order = 1)]
        public InterpolationPointType[] InterpolationPoint
        {
            get
            {
                return this.interpolationPointField;
            }
            set
            {
                this.interpolationPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModeType mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeSpecified
        {
            get
            {
                return this.modeFieldSpecified;
            }
            set
            {
                this.modeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MethodType method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool methodSpecified
        {
            get
            {
                return this.methodFieldSpecified;
            }
            set
            {
                this.methodFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("InterpolationPoint", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class InterpolationPointType : ExpressionType
    {

        private double dataField;

        private ParameterValueType valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public double Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ParameterValueType Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    public enum ModeType
    {

        /// <remarks/>
        linear,

        /// <remarks/>
        cosine,

        /// <remarks/>
        cubic,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    public enum MethodType
    {

        /// <remarks/>
        numeric,

        /// <remarks/>
        color,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("ShadedRelief", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class ShadedReliefType
    {

        private bool brightnessOnlyField;

        private bool brightnessOnlyFieldSpecified;

        private double reliefFactorField;

        private bool reliefFactorFieldSpecified;

        /// <remarks/>
        public bool BrightnessOnly
        {
            get
            {
                return this.brightnessOnlyField;
            }
            set
            {
                this.brightnessOnlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BrightnessOnlySpecified
        {
            get
            {
                return this.brightnessOnlyFieldSpecified;
            }
            set
            {
                this.brightnessOnlyFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double ReliefFactor
        {
            get
            {
                return this.reliefFactorField;
            }
            set
            {
                this.reliefFactorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReliefFactorSpecified
        {
            get
            {
                return this.reliefFactorFieldSpecified;
            }
            set
            {
                this.reliefFactorFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("ImageOutline", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class ImageOutlineType
    {

        private SymbolizerType itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LineSymbolizer", typeof(LineSymbolizerType))]
        [System.Xml.Serialization.XmlElementAttribute("PolygonSymbolizer", typeof(PolygonSymbolizerType))]
        public SymbolizerType Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("FormatNumber", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class FormatNumberType : FunctionType
    {

        private ParameterValueType numericValueField;

        private string patternField;

        private string negativePatternField;

        private string decimalPointField;

        private string groupingSeparatorField;

        public FormatNumberType()
        {
            this.decimalPointField = ".";
            this.groupingSeparatorField = ",";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterValueType NumericValue
        {
            get
            {
                return this.numericValueField;
            }
            set
            {
                this.numericValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Pattern
        {
            get
            {
                return this.patternField;
            }
            set
            {
                this.patternField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string NegativePattern
        {
            get
            {
                return this.negativePatternField;
            }
            set
            {
                this.negativePatternField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(".")]
        public string decimalPoint
        {
            get
            {
                return this.decimalPointField;
            }
            set
            {
                this.decimalPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(",")]
        public string groupingSeparator
        {
            get
            {
                return this.groupingSeparatorField;
            }
            set
            {
                this.groupingSeparatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("FormatDate", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class FormatDateType : FunctionType
    {

        private ParameterValueType dateValueField;

        private string patternField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterValueType DateValue
        {
            get
            {
                return this.dateValueField;
            }
            set
            {
                this.dateValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Pattern
        {
            get
            {
                return this.patternField;
            }
            set
            {
                this.patternField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("Substring", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class SubstringType : FunctionType
    {

        private ParameterValueType stringValueField;

        private ParameterValueType positionField;

        private ParameterValueType lengthField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterValueType StringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ParameterValueType Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ParameterValueType Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("Concatenate", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class ConcatenateType : FunctionType
    {

        private ParameterValueType[] stringValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StringValue", Order = 0)]
        public ParameterValueType[] StringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("ChangeCase", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class ChangeCaseType : FunctionType
    {

        private ParameterValueType stringValueField;

        private directionType directionField;

        private bool directionFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterValueType StringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public directionType direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool directionSpecified
        {
            get
            {
                return this.directionFieldSpecified;
            }
            set
            {
                this.directionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    public enum directionType
    {

        /// <remarks/>
        toUpper,

        /// <remarks/>
        toLower,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("Trim", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class TrimType : FunctionType
    {

        private ParameterValueType stringValueField;

        private stripOffPositionType stripOffPositionField;

        private bool stripOffPositionFieldSpecified;

        private string stripOffCharField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterValueType StringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public stripOffPositionType stripOffPosition
        {
            get
            {
                return this.stripOffPositionField;
            }
            set
            {
                this.stripOffPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stripOffPositionSpecified
        {
            get
            {
                return this.stripOffPositionFieldSpecified;
            }
            set
            {
                this.stripOffPositionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stripOffChar
        {
            get
            {
                return this.stripOffCharField;
            }
            set
            {
                this.stripOffCharField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    public enum stripOffPositionType
    {

        /// <remarks/>
        leading,

        /// <remarks/>
        trailing,

        /// <remarks/>
        both,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("StringPosition", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class StringPositionType : FunctionType
    {

        private ParameterValueType lookupStringField;

        private ParameterValueType stringValueField;

        private searchDirectionType searchDirectionField;

        private bool searchDirectionFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterValueType LookupString
        {
            get
            {
                return this.lookupStringField;
            }
            set
            {
                this.lookupStringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ParameterValueType StringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public searchDirectionType searchDirection
        {
            get
            {
                return this.searchDirectionField;
            }
            set
            {
                this.searchDirectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchDirectionSpecified
        {
            get
            {
                return this.searchDirectionFieldSpecified;
            }
            set
            {
                this.searchDirectionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    public enum searchDirectionType
    {

        /// <remarks/>
        frontToBack,

        /// <remarks/>
        backToFront,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("StringLength", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class StringLengthType : FunctionType
    {

        private ParameterValueType stringValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterValueType StringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("FeatureTypeStyle", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class FeatureTypeStyleType
    {

        private string nameField;

        private DescriptionType descriptionField;

        private System.Xml.XmlQualifiedName featureTypeNameField;

        private string[] semanticTypeIdentifierField;

        private object[] itemsField;

        private VersionType versionField;

        private bool versionFieldSpecified;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public DescriptionType Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlQualifiedName FeatureTypeName
        {
            get
            {
                return this.featureTypeNameField;
            }
            set
            {
                this.featureTypeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SemanticTypeIdentifier")]
        public string[] SemanticTypeIdentifier
        {
            get
            {
                return this.semanticTypeIdentifierField;
            }
            set
            {
                this.semanticTypeIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OnlineResource", typeof(OnlineResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("Rule", typeof(RuleType))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VersionType version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("Rule", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class RuleType
    {

        private string nameField;

        private DescriptionType descriptionField;

        private LegendGraphicType legendGraphicField;

        private object itemField;

        private double minScaleDenominatorField;

        private bool minScaleDenominatorFieldSpecified;

        private double maxScaleDenominatorField;

        private bool maxScaleDenominatorFieldSpecified;

        private SymbolizerType[] itemsField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public DescriptionType Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public LegendGraphicType LegendGraphic
        {
            get
            {
                return this.legendGraphicField;
            }
            set
            {
                this.legendGraphicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Filter", typeof(FilterType), Namespace = "http://www.opengis.net/ogc")]
        [System.Xml.Serialization.XmlElementAttribute("ElseFilter", typeof(ElseFilterType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public double MinScaleDenominator
        {
            get
            {
                return this.minScaleDenominatorField;
            }
            set
            {
                this.minScaleDenominatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinScaleDenominatorSpecified
        {
            get
            {
                return this.minScaleDenominatorFieldSpecified;
            }
            set
            {
                this.minScaleDenominatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double MaxScaleDenominator
        {
            get
            {
                return this.maxScaleDenominatorField;
            }
            set
            {
                this.maxScaleDenominatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxScaleDenominatorSpecified
        {
            get
            {
                return this.maxScaleDenominatorFieldSpecified;
            }
            set
            {
                this.maxScaleDenominatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LineSymbolizer", typeof(LineSymbolizerType))]
        [System.Xml.Serialization.XmlElementAttribute("PointSymbolizer", typeof(PointSymbolizerType))]
        [System.Xml.Serialization.XmlElementAttribute("PolygonSymbolizer", typeof(PolygonSymbolizerType))]
        [System.Xml.Serialization.XmlElementAttribute("RasterSymbolizer", typeof(RasterSymbolizerType))]
        [System.Xml.Serialization.XmlElementAttribute("TextSymbolizer", typeof(TextSymbolizerType))]
        public SymbolizerType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("LegendGraphic", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class LegendGraphicType
    {

        private GraphicType graphicField;

        /// <remarks/>
        public GraphicType Graphic
        {
            get
            {
                return this.graphicField;
            }
            set
            {
                this.graphicField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("ElseFilter", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class ElseFilterType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/se")]
    [System.Xml.Serialization.XmlRootAttribute("CoverageStyle", Namespace = "http://www.opengis.net/se", IsNullable = false)]
    public partial class CoverageStyleType
    {

        private string nameField;

        private DescriptionType descriptionField;

        private string coverageNameField;

        private string[] semanticTypeIdentifierField;

        private object[] itemsField;

        private VersionType versionField;

        private bool versionFieldSpecified;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public DescriptionType Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string CoverageName
        {
            get
            {
                return this.coverageNameField;
            }
            set
            {
                this.coverageNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SemanticTypeIdentifier")]
        public string[] SemanticTypeIdentifier
        {
            get
            {
                return this.semanticTypeIdentifierField;
            }
            set
            {
                this.semanticTypeIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OnlineResource", typeof(OnlineResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("Rule", typeof(RuleType))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VersionType version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    [System.Xml.Serialization.XmlRootAttribute("SortBy", Namespace = "http://www.opengis.net/ogc", IsNullable = false)]
    public partial class SortByType
    {

        private SortPropertyType[] sortPropertyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SortProperty")]
        public SortPropertyType[] SortProperty
        {
            get
            {
                return this.sortPropertyField;
            }
            set
            {
                this.sortPropertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    public partial class SortPropertyType
    {

        private PropertyNameType propertyNameField;

        private SortOrderType sortOrderField;

        private bool sortOrderFieldSpecified;

        /// <remarks/>
        public PropertyNameType PropertyName
        {
            get
            {
                return this.propertyNameField;
            }
            set
            {
                this.propertyNameField = value;
            }
        }

        /// <remarks/>
        public SortOrderType SortOrder
        {
            get
            {
                return this.sortOrderField;
            }
            set
            {
                this.sortOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortOrderSpecified
        {
            get
            {
                return this.sortOrderFieldSpecified;
            }
            set
            {
                this.sortOrderFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    public enum SortOrderType
    {

        /// <remarks/>
        DESC,

        /// <remarks/>
        ASC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ogc", IsNullable = false)]
    public partial class Filter_Capabilities
    {

        private Scalar_CapabilitiesType scalar_CapabilitiesField;

        private object[] id_CapabilitiesField;

        /// <remarks/>
        public Scalar_CapabilitiesType Scalar_Capabilities
        {
            get
            {
                return this.scalar_CapabilitiesField;
            }
            set
            {
                this.scalar_CapabilitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EID", typeof(EID), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FID", typeof(FID), IsNullable = false)]
        public object[] Id_Capabilities
        {
            get
            {
                return this.id_CapabilitiesField;
            }
            set
            {
                this.id_CapabilitiesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    public partial class Scalar_CapabilitiesType
    {

        private LogicalOperators logicalOperatorsField;

        private ComparisonOperatorsType comparisonOperatorsField;

        private object[] arithmeticOperatorsField;

        /// <remarks/>
        public LogicalOperators LogicalOperators
        {
            get
            {
                return this.logicalOperatorsField;
            }
            set
            {
                this.logicalOperatorsField = value;
            }
        }

        /// <remarks/>
        public ComparisonOperatorsType ComparisonOperators
        {
            get
            {
                return this.comparisonOperatorsField;
            }
            set
            {
                this.comparisonOperatorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Functions", typeof(FunctionsType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SimpleArithmetic", typeof(SimpleArithmetic), IsNullable = false)]
        public object[] ArithmeticOperators
        {
            get
            {
                return this.arithmeticOperatorsField;
            }
            set
            {
                this.arithmeticOperatorsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ogc", IsNullable = false)]
    public partial class LogicalOperators
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    public partial class ComparisonOperatorsType
    {

        private ComparisonOperatorType[] comparisonOperatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComparisonOperator")]
        public ComparisonOperatorType[] ComparisonOperator
        {
            get
            {
                return this.comparisonOperatorField;
            }
            set
            {
                this.comparisonOperatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    public enum ComparisonOperatorType
    {

        /// <remarks/>
        LessThan,

        /// <remarks/>
        GreaterThan,

        /// <remarks/>
        LessThanEqualTo,

        /// <remarks/>
        GreaterThanEqualTo,

        /// <remarks/>
        EqualTo,

        /// <remarks/>
        NotEqualTo,

        /// <remarks/>
        Like,

        /// <remarks/>
        Between,

        /// <remarks/>
        NullCheck,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    public partial class FunctionsType
    {

        private FunctionNamesType functionNamesField;

        /// <remarks/>
        public FunctionNamesType FunctionNames
        {
            get
            {
                return this.functionNamesField;
            }
            set
            {
                this.functionNamesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    public partial class FunctionNamesType
    {

        private FunctionNameType[] functionNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FunctionName")]
        public FunctionNameType[] FunctionName
        {
            get
            {
                return this.functionNameField;
            }
            set
            {
                this.functionNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ogc")]
    public partial class FunctionNameType
    {

        private string nArgsField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nArgs
        {
            get
            {
                return this.nArgsField;
            }
            set
            {
                this.nArgsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ogc", IsNullable = false)]
    public partial class SimpleArithmetic
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ogc", IsNullable = false)]
    public partial class EID
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ogc")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ogc", IsNullable = false)]
    public partial class FID
    {
    }
}