// Portions copyright 2005, 2006 - Morten Nielsen (www.iter.dk)
// Portions copyright 2006, 2007 - Rory Plaire (codekaizen@gmail.com)
//
// This file is part of SharpMap.
// SharpMap is free software; you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// 
// SharpMap is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.

// You should have received a copy of the GNU Lesser General Public License
// along with SharpMap; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 

using System.Data;

namespace SharpMap.Features
{
    /// <summary>
    /// Represents a row of data in a <see cref="FeatureDataTable{TOid}"/>.
    /// </summary>
    /// <typeparam name="TOid">Type of the object id (OID).</typeparam>
    public class FeatureDataRow<TOid> : FeatureDataRow
    {
        #region Constructors

        internal FeatureDataRow(DataRowBuilder rb)
            : base(rb)
        {
        }

        #endregion

        /// <summary>
        /// The feature's unique object id.
        /// </summary>
        /// <remarks>
        /// The OID is usually generated by the system which created the feature.
        /// </remarks>
        public TOid Id
        {
            get
            {
                if (Table == null)
                {
                    return default(TOid);
                }

                return (TOid) ItemArray[Table.IdColumn.Ordinal];
            }
        }

        /// <summary>
        /// The table to which this row belongs.
        /// </summary>
        public new FeatureDataTable<TOid> Table
        {
            get { return base.Table as FeatureDataTable<TOid>; }
        }
    }
}